# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ab7cfb5df9ccc444090f7092bb76f8e833d722d135bcdfdbe625e227fc0dc3d3789d951c720b1c21e7d95101a479e9c5c3f478fa5c67025e1a56a37ee240120

test:
  secret_key_base: fc37c7bb53c4b36254801eb025dae55e2044b2aebf5f5b6607d0a8a6db76be56dd49f76cca33c8b42f6ad706d6cda0dc1cd3bee2c229249240beca72e0436a9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
